import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppHeader, Button, ChoiceRow, Pill, Screen } from '@/components/ui';
import { useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';

type Option = { label: string; detail: string; icon: keyof typeof Feather.glyphMap };
type Step = { title: string; subtitle: string; key: 'role' | 'company' | 'experience' | 'difficulty' | 'type'; options: Option[] };
const steps: Step[] = [
  { title: 'Choose your role', subtitle: 'What are you preparing for?', key: 'role', options: [{ label: 'Flutter Developer', detail: 'Mobile Development · 1–3 years', icon: 'smartphone' }, { label: 'React Developer', detail: 'Web Development · 1–3 years', icon: 'code' }, { label: 'Product Designer', detail: 'Design · 2–5 years', icon: 'pen-tool' }] },
  { title: 'Choose a company', subtitle: 'Optional context helps us set the tone.', key: 'company', options: [{ label: 'General interview', detail: 'Practice transferable skills', icon: 'globe' }, { label: 'Google', detail: 'Structured product thinking', icon: 'search' }, { label: 'Startup', detail: 'Ownership and ambiguity', icon: 'zap' }, { label: 'FinTech', detail: 'Trust, scale, and accuracy', icon: 'briefcase' }] },
  { title: 'Set your experience', subtitle: 'We’ll match the depth to your journey.', key: 'experience', options: [{ label: 'Use experience from resume', detail: 'Detected as 1.2 years', icon: 'file-text' }, { label: '0–1 years', detail: 'Early career / fresher', icon: 'sunrise' }, { label: '1–2 years', detail: 'Building strong foundations', icon: 'trending-up' }, { label: '3–5 years', detail: 'Experienced practitioner', icon: 'award' }] },
  { title: 'Set the difficulty', subtitle: 'How much should the session stretch you?', key: 'difficulty', options: [{ label: 'Adaptive', detail: 'Adjusts based on your answers', icon: 'sliders' }, { label: 'Medium', detail: 'A balanced interview session', icon: 'minus' }, { label: 'Hard', detail: 'Push me beyond the obvious', icon: 'zap' }] },
  { title: 'Choose interview type', subtitle: 'What would you like to practice?', key: 'type', options: [{ label: 'Technical interview', detail: 'Role knowledge and problem solving', icon: 'cpu' }, { label: 'Behavioral interview', detail: 'Stories, impact, and communication', icon: 'message-circle' }, { label: 'Full mock interview', detail: 'A realistic mix of everything', icon: 'layers' }] },
];
export default function Create() {
  const colors = useColors();
  const { config, setConfig, startInterview, resume } = useApp();
  const [step, setStep] = useState(0);
  const review = step === steps.length;
  const current = steps[Math.min(step, steps.length - 1)];
  const selected = current ? config[current.key] : '';
  const choose = (label: string) => setConfig({ [current.key]: label });
  const next = () => step < steps.length ? setStep(step + 1) : router.push('/interview');
  const stepTitle = review ? 'Review your session' : current.title;
  const stepSubtitle = review ? 'Everything looks good? Let’s make this a useful rep.' : current.subtitle;
  return <Screen><AppHeader title="New interview" subtitle={`Step ${Math.min(step + 1, steps.length + 1)} of ${steps.length + 1}`} onBack={() => step > 0 ? setStep(step - 1) : router.back()} /><View style={styles.progress}><View style={[styles.progressFill, { width: `${((step + 1) / (steps.length + 1)) * 100}%`, backgroundColor: colors.primary }]} /></View><View style={styles.stepCopy}><Text style={[styles.eyebrow, { color: colors.primary }]}>SETUP YOUR SESSION</Text><Text style={[styles.title, { color: colors.foreground }]}>{stepTitle}</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>{stepSubtitle}</Text></View>{!review ? <>{current.options.map((option) => <ChoiceRow key={option.label} label={option.label} detail={option.detail} icon={option.icon} selected={selected === option.label} onPress={() => choose(option.label)} />)}{step === 0 ? <Pressable onPress={() => router.push('/resume')} style={styles.secondaryLink}><Feather name="upload-cloud" size={15} color={colors.primary} /><Text style={[styles.linkText, { color: colors.primary }]}>Choose a different resume</Text></Pressable> : null}</> : <><View style={[styles.summary, { backgroundColor: colors.secondary }]}><View style={styles.summaryTop}><Text style={[styles.summaryLabel, { color: colors.mutedForeground }]}>SESSION SUMMARY</Text><Pill label="Ready to start" tone="success" /></View><Text style={[styles.summaryTitle, { color: colors.foreground }]}>{config.role}</Text><Text style={[styles.summaryMeta, { color: colors.mutedForeground }]}>{config.company} · {config.experience} · {config.difficulty}</Text><Text style={[styles.summaryMeta, { color: colors.mutedForeground }]}>{config.type} · {config.questions} questions · about 20 min</Text><Pressable onPress={() => router.push('/resume')}><Text style={[styles.resumeLink, { color: colors.primary }]}>Using {resume.name} · Change</Text></Pressable></View><Text style={[styles.questionLabel, { color: colors.foreground }]}>Session length</Text><View style={styles.lengthRow}>{[5, 10, 15].map((length) => <Pressable key={length} onPress={() => setConfig({ questions: length })} style={[styles.length, { backgroundColor: config.questions === length ? colors.primary : colors.card, borderColor: config.questions === length ? colors.primary : colors.border }]}><Text style={[styles.lengthText, { color: config.questions === length ? colors.primaryForeground : colors.foreground }]}>{length}</Text><Text style={[styles.lengthSub, { color: config.questions === length ? colors.primaryForeground : colors.mutedForeground }]}>questions</Text></Pressable>)}</View></> }<View style={styles.bottom}><Button label={review ? 'Start interview' : 'Continue'} icon="arrow-right" onPress={() => { if (review) startInterview(); next(); }} /></View></Screen>;
}
const styles = StyleSheet.create({ progress: { height: 6, backgroundColor: '#EEF1FA', borderRadius: 5, overflow: 'hidden', marginTop: 6 }, progressFill: { height: '100%', borderRadius: 5 }, stepCopy: { marginTop: 34, marginBottom: 23 }, eyebrow: { fontFamily: 'Inter_700Bold', letterSpacing: 1.4, fontSize: 10 }, title: { fontFamily: 'Inter_700Bold', fontSize: 29, marginTop: 11 }, subtitle: { fontFamily: 'Inter_400Regular', fontSize: 13, marginTop: 7 }, summary: { borderRadius: 19, padding: 16, marginTop: 8 }, summaryTop: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, summaryLabel: { fontFamily: 'Inter_700Bold', fontSize: 10, letterSpacing: 1.2 }, summaryTitle: { fontFamily: 'Inter_700Bold', fontSize: 18, marginTop: 15 }, summaryMeta: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 5 }, resumeLink: { fontFamily: 'Inter_600SemiBold', fontSize: 11, marginTop: 13 }, secondaryLink: { flexDirection: 'row', alignItems: 'center', gap: 7, marginTop: 2 }, linkText: { fontFamily: 'Inter_600SemiBold', fontSize: 12 }, questionLabel: { fontFamily: 'Inter_700Bold', fontSize: 14, marginTop: 23, marginBottom: 10 }, lengthRow: { flexDirection: 'row', gap: 8 }, length: { flex: 1, borderRadius: 15, borderWidth: 1, padding: 12, alignItems: 'center' }, lengthText: { fontFamily: 'Inter_700Bold', fontSize: 18 }, lengthSub: { fontFamily: 'Inter_400Regular', fontSize: 9, marginTop: 2 }, bottom: { marginTop: 28, paddingBottom: 14 } });