import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { ActivityIndicator, Pressable, StyleSheet, Text, View } from 'react-native';
import { AppHeader, Button, Field, Pill, Screen, SectionTitle } from '@/components/ui';
import { useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';

export default function Resume() {
  const colors = useColors();
  const { resume, saveResume } = useApp();
  const [pasteOpen, setPasteOpen] = useState(false);
  const [pasteText, setPasteText] = useState('');
  const simulateUpload = () => {
    saveResume({ status: 'analyzing', name: 'Meraj_Resume_v2.pdf', source: 'upload' });
    setTimeout(() => saveResume({ status: 'ready', skills: ['Flutter', 'Dart', 'Riverpod', 'REST APIs', 'Clean Architecture', 'Firebase'] }), 1100);
  };
  const savePastedResume = () => {
    if (!pasteText.trim()) return;
    saveResume({ status: 'analyzing', name: 'Pasted resume', source: 'paste' });
    setPasteOpen(false);
    setTimeout(() => saveResume({ status: 'ready', skills: ['Flutter', 'Dart', 'Firebase', 'REST APIs', 'Provider', 'Supabase'] }), 1100);
  };
  return <Screen><AppHeader title="My resume" onBack={() => router.back()} right={<Pressable><Feather name="more-horizontal" size={20} color={colors.foreground} /></Pressable>} /><View style={[styles.resumeCard, { backgroundColor: colors.navy }]}><View style={[styles.fileIcon, { backgroundColor: colors.mint }]}>{resume.status === 'analyzing' ? <ActivityIndicator color={colors.navy} /> : <Feather name="file-text" size={24} color={colors.navy} />}</View><View style={styles.resumeCopy}><Text style={styles.resumeName}>{resume.status === 'analyzing' ? 'Analyzing your resume…' : resume.name}</Text><Text style={styles.resumeMeta}>{resume.status === 'analyzing' ? 'Extracting skills and experience' : 'Updated 4 days ago · 1.2 MB'}</Text><Pill label={resume.status === 'analyzing' ? 'Processing' : 'Default resume'} tone="success" /></View><Feather name={resume.status === 'analyzing' ? 'loader' : 'check-circle'} size={19} color={colors.mint} /></View><Button label="Upload another resume" icon="upload-cloud" onPress={simulateUpload} variant="secondary" /><SectionTitle title="Resume analysis" action="Edit" /><View style={[styles.analysis, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.analysisRow}><View><Text style={[styles.analysisValue, { color: colors.foreground }]}>{resume.experience}</Text><Text style={[styles.analysisLabel, { color: colors.mutedForeground }]}>Experience</Text></View><View><Text style={[styles.analysisValue, { color: colors.foreground }]}>{resume.projects}</Text><Text style={[styles.analysisLabel, { color: colors.mutedForeground }]}>Projects</Text></View><View><Text style={[styles.analysisValue, { color: colors.foreground }]}>{resume.skills.length}</Text><Text style={[styles.analysisLabel, { color: colors.mutedForeground }]}>Skills</Text></View></View><View style={[styles.divider, { backgroundColor: colors.border }]} /><Text style={[styles.smallLabel, { color: colors.mutedForeground }]}>Primary skills</Text><View style={styles.skillWrap}>{resume.skills.map((skill) => <Pill key={skill} label={skill} tone="muted" />)}</View></View><SectionTitle title="Or paste your resume" /><Text style={[styles.helper, { color: colors.mutedForeground }]}>No file? Paste your resume text and we’ll use the same analysis.</Text>{pasteOpen ? <View><Field value={pasteText} onChangeText={setPasteText} placeholder="Paste your resume here…" multiline /><Button label="Analyze pasted resume" icon="star" onPress={savePastedResume} /></View> : <Pressable onPress={() => setPasteOpen(true)} style={[styles.paste, { backgroundColor: colors.secondary, borderColor: colors.border }]}><Feather name="clipboard" size={18} color={colors.primary} /><Text style={[styles.pasteText, { color: colors.foreground }]}>Paste resume text</Text><Feather name="chevron-right" size={17} color={colors.mutedForeground} /></Pressable>}</Screen>;
}
const styles = StyleSheet.create({ resumeCard: { borderRadius: 22, padding: 17, flexDirection: 'row', alignItems: 'center', marginTop: 8, marginBottom: 13 }, fileIcon: { width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, resumeCopy: { flex: 1, marginLeft: 12 }, resumeName: { color: '#FFFFFF', fontFamily: 'Inter_600SemiBold', fontSize: 14 }, resumeMeta: { color: '#BFCBE5', fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 4, marginBottom: 8 }, analysis: { borderRadius: 20, borderWidth: 1, padding: 17 }, analysisRow: { flexDirection: 'row', justifyContent: 'space-between' }, analysisValue: { fontFamily: 'Inter_700Bold', fontSize: 21 }, analysisLabel: { fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 3 }, divider: { height: 1, marginVertical: 17 }, smallLabel: { fontFamily: 'Inter_500Medium', fontSize: 11, marginBottom: 10 }, skillWrap: { flexDirection: 'row', gap: 7, flexWrap: 'wrap' }, helper: { fontFamily: 'Inter_400Regular', fontSize: 12, lineHeight: 18, marginTop: -2, marginBottom: 12 }, paste: { borderRadius: 17, borderWidth: 1, padding: 15, flexDirection: 'row', alignItems: 'center', gap: 11 }, pasteText: { flex: 1, fontFamily: 'Inter_600SemiBold', fontSize: 13 } });