import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { AppHeader, Pill, ProgressBar, Screen } from '@/components/ui';
import { useColors } from '@/hooks/useColors';

const questions = [
  { q: 'Can you walk me through one Flutter project you’ve worked on?', score: '8.5', answer: 'I built an OTT application where I owned the mobile architecture and worked closely with the API team.', feedback: 'Strong project framing. Add one specific trade-off to make the story more memorable.' },
  { q: 'How did you handle state management in your Flutter application?', score: '7.0', answer: 'I used Provider to keep state predictable and separate from the UI layer.', feedback: 'Good fundamentals. Go deeper on dependency injection and provider lifecycle.' },
  { q: 'How did you handle API errors?', score: '8.0', answer: 'I modelled failures explicitly and gave the user a recoverable state instead of a blank screen.', feedback: 'Clear and practical. Mention how you observe and debug errors in production.' },
];
export default function Review() {
  const colors = useColors();
  const [index, setIndex] = useState(0);
  const item = questions[index];
  return <Screen><AppHeader title="Question review" subtitle={`${index + 1} of ${questions.length}`} onBack={() => router.back()} /><View style={styles.selector}>{questions.map((_, itemIndex) => <Pressable key={itemIndex} onPress={() => setIndex(itemIndex)} style={[styles.selectorDot, { backgroundColor: index === itemIndex ? colors.primary : colors.secondary }]}><Text style={[styles.selectorText, { color: index === itemIndex ? colors.primaryForeground : colors.mutedForeground }]}>{itemIndex + 1}</Text></Pressable>)}</View><View style={[styles.questionCard, { backgroundColor: colors.card, borderColor: colors.border }]}><Text style={[styles.eyebrow, { color: colors.primary }]}>QUESTION {index + 1}</Text><Text style={[styles.question, { color: colors.foreground }]}>{item.q}</Text></View><Text style={[styles.section, { color: colors.foreground }]}>Your answer</Text><View style={[styles.answer, { backgroundColor: colors.secondary }]}><Text style={[styles.answerText, { color: colors.foreground }]}>{item.answer}</Text></View><View style={styles.scoreHeader}><Text style={[styles.section, { color: colors.foreground, marginBottom: 0 }]}>AI evaluation</Text><Pill label={`${item.score} / 10`} tone="success" /></View><View style={[styles.feedback, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.feedbackTop}><Feather name="check-circle" size={17} color={colors.success} /><Text style={[styles.feedbackTitle, { color: colors.foreground }]}>Good answer</Text></View><Text style={[styles.feedbackBody, { color: colors.mutedForeground }]}>{item.feedback}</Text><Text style={[styles.missing, { color: colors.foreground }]}>What was missing</Text><Text style={[styles.feedbackBody, { color: colors.mutedForeground }]}>A more specific example would make the impact easier to evaluate.</Text></View><View style={styles.navigation}><Pressable disabled={index === 0} onPress={() => setIndex(index - 1)}><Text style={[styles.navText, { color: index === 0 ? colors.input : colors.primary }]}>← Previous</Text></Pressable><Text style={[styles.count, { color: colors.mutedForeground }]}>{index + 1} / {questions.length}</Text><Pressable disabled={index === questions.length - 1} onPress={() => setIndex(index + 1)}><Text style={[styles.navText, { color: index === questions.length - 1 ? colors.input : colors.primary }]}>Next →</Text></Pressable></View></Screen>;
}
const styles = StyleSheet.create({ selector: { flexDirection: 'row', gap: 9, marginTop: 10, marginBottom: 17 }, selectorDot: { width: 34, height: 34, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, selectorText: { fontFamily: 'Inter_700Bold', fontSize: 12 }, questionCard: { borderWidth: 1, borderRadius: 20, padding: 18 }, eyebrow: { fontFamily: 'Inter_700Bold', letterSpacing: 1.3, fontSize: 10 }, question: { fontFamily: 'Inter_700Bold', fontSize: 20, lineHeight: 28, marginTop: 11 }, section: { fontFamily: 'Inter_700Bold', fontSize: 16, marginTop: 23, marginBottom: 10 }, answer: { borderRadius: 17, padding: 16 }, answerText: { fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 20 }, scoreHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, feedback: { borderWidth: 1, borderRadius: 18, padding: 16 }, feedbackTop: { flexDirection: 'row', gap: 8, alignItems: 'center' }, feedbackTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, feedbackBody: { fontFamily: 'Inter_400Regular', fontSize: 11, lineHeight: 17, marginTop: 9 }, missing: { fontFamily: 'Inter_700Bold', fontSize: 12, marginTop: 18 }, navigation: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginTop: 27, marginBottom: 20 }, navText: { fontFamily: 'Inter_600SemiBold', fontSize: 12 }, count: { fontFamily: 'Inter_500Medium', fontSize: 11 } });