import { Feather } from '@expo/vector-icons';
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { Screen, SectionTitle, Stat } from '@/components/ui';
import { useColors } from '@/hooks/useColors';

export default function Analytics() {
  const colors = useColors();
  const points = [58, 66, 63, 74, 71, 82, 78, 86];
  const skills: Array<{ label: string; value: number; color: string }> = [
    { label: 'Technical knowledge', value: 86, color: colors.primary },
    { label: 'Communication', value: 78, color: colors.coral },
    { label: 'Problem solving', value: 84, color: colors.violet },
    { label: 'Confidence', value: 75, color: colors.yellow },
  ];
  return <Screen><SectionTitle title="Analytics" action="Last 30 days" /><Text style={[styles.intro, { color: colors.mutedForeground }]}>A clearer view of how your interview readiness is changing.</Text><View style={styles.stats}><Stat label="Average score" value="78%" change="+14% overall" icon="trending-up" /><Stat label="Completion rate" value="92%" change="+5% this month" icon="check-circle" /></View><View style={[styles.chartCard, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={styles.chartHeader}><View><Text style={[styles.chartTitle, { color: colors.foreground }]}>Score over time</Text><Text style={[styles.chartSub, { color: colors.mutedForeground }]}>Last 8 interviews</Text></View><Feather name="more-horizontal" size={19} color={colors.mutedForeground} /></View><View style={styles.chart}><View style={[styles.axis, { backgroundColor: colors.border, top: 0 }]} /><View style={[styles.axis, { backgroundColor: colors.border, top: '50%' }]} /><View style={[styles.axis, { backgroundColor: colors.border, bottom: 0 }]} />{points.map((point, index) => <View key={point + index} style={styles.barWrap}><View style={[styles.bar, { height: `${point}%`, backgroundColor: index === points.length - 1 ? colors.primary : colors.mint }]} /><Text style={[styles.barLabel, { color: colors.mutedForeground }]}>{index + 1}</Text></View>)}</View></View><SectionTitle title="Skill distribution" /><View style={[styles.skillCard, { backgroundColor: colors.card, borderColor: colors.border }]}>{skills.map((skill) => <View key={skill.label} style={styles.skill}><View style={styles.skillTop}><Text style={[styles.skillLabel, { color: colors.foreground }]}>{skill.label}</Text><Text style={[styles.skillValue, { color: colors.foreground }]}>{skill.value}%</Text></View><View style={[styles.track, { backgroundColor: colors.muted }]}><View style={[styles.skillFill, { width: `${skill.value}%`, backgroundColor: skill.color }]} /></View></View>)}</View><View style={[styles.insight, { backgroundColor: colors.secondary }]}><View style={[styles.insightIcon, { backgroundColor: colors.mint }]}><Feather name="star" size={17} color={colors.navy} /></View><View style={styles.insightCopy}><Text style={[styles.insightTitle, { color: colors.foreground }]}>AI insight</Text><Text style={[styles.insightText, { color: colors.mutedForeground }]}>Your technical performance improved by 14% over your last five interviews.</Text></View></View></Screen>;
}
const styles = StyleSheet.create({ intro: { fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 19, marginTop: -4, marginBottom: 20 }, stats: { flexDirection: 'row', justifyContent: 'space-between' }, chartCard: { borderRadius: 20, borderWidth: 1, padding: 16, marginTop: 10 }, chartHeader: { flexDirection: 'row', justifyContent: 'space-between' }, chartTitle: { fontFamily: 'Inter_700Bold', fontSize: 15 }, chartSub: { fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 3 }, chart: { height: 145, marginTop: 20, flexDirection: 'row', alignItems: 'flex-end', justifyContent: 'space-between', position: 'relative', paddingHorizontal: 8 }, axis: { position: 'absolute', left: 0, right: 0, height: 1 }, barWrap: { height: '100%', alignItems: 'center', justifyContent: 'flex-end', width: 22 }, bar: { width: 17, minHeight: 14, borderRadius: 7 }, barLabel: { fontFamily: 'Inter_500Medium', fontSize: 9, marginTop: 6 }, skillCard: { borderRadius: 20, borderWidth: 1, padding: 16 }, skill: { marginBottom: 16 }, skillTop: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 }, skillLabel: { fontFamily: 'Inter_500Medium', fontSize: 12 }, skillValue: { fontFamily: 'Inter_700Bold', fontSize: 12 }, track: { height: 7, borderRadius: 7, overflow: 'hidden' }, skillFill: { height: 7, borderRadius: 7 }, insight: { borderRadius: 18, padding: 15, flexDirection: 'row', marginTop: 20 }, insightIcon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, insightCopy: { flex: 1, marginLeft: 11 }, insightTitle: { fontFamily: 'Inter_700Bold', fontSize: 13 }, insightText: { fontFamily: 'Inter_400Regular', fontSize: 11, lineHeight: 16, marginTop: 4 } });