import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { SectionTitle, Stat } from '@/components/ui';
import { useColors } from '@/hooks/useColors';

export default function Home() {
  const colors = useColors();
  const insets = useSafeAreaInsets();
  return <View style={[styles.container, { backgroundColor: colors.background, paddingTop: insets.top + 14 }]}><View style={styles.header}><View><Text style={[styles.greeting, { color: colors.foreground }]}>Good morning, Meraj</Text><Text style={[styles.subtitle, { color: colors.mutedForeground }]}>Ready for your next interview?</Text></View><Pressable onPress={() => router.push('/profile')} style={[styles.avatar, { backgroundColor: colors.navy }]}><Text style={styles.avatarText}>MK</Text></Pressable></View>
    <Pressable onPress={() => router.push('/create')} style={({ pressed }) => [styles.quickStart, { backgroundColor: colors.navy, opacity: pressed ? 0.85 : 1 }]}><View style={styles.quickCopy}><Text style={styles.quickEyebrow}>YOUR NEXT REP</Text><Text style={styles.quickTitle}>Start a new interview</Text><Text style={styles.quickSubtitle}>Practice with feedback that moves you forward.</Text><View style={styles.startAction}><Text style={[styles.startText, { color: colors.navy }]}>Start now</Text><Feather name="arrow-up-right" size={17} color={colors.navy} /></View></View><View style={[styles.orbit, { borderColor: colors.mint }]}><Feather name="mic" size={28} color={colors.mint} /></View></Pressable>
    <SectionTitle title="Your performance" action="View analytics" onAction={() => router.push('/analytics')} /><View style={styles.stats}><Stat label="Avg. score" value="78%" change="+8% this month" icon="trending-up" /><Stat label="Interviews" value="12" change="+3 this week" icon="layers" /><Stat label="Best score" value="91%" icon="award" /><Stat label="Current streak" value="4 days" icon="zap" /></View>
    <SectionTitle title="Recent interviews" action="See all" onAction={() => router.push('/interviews')} /><View style={[styles.recent, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.recentIcon, { backgroundColor: colors.accent }]}><Feather name="code" size={19} color={colors.accentForeground} /></View><View style={styles.recentCopy}><Text style={[styles.recentTitle, { color: colors.foreground }]}>Flutter Developer</Text><Text style={[styles.recentMeta, { color: colors.mutedForeground }]}>Technical · 2 days ago · 18 min</Text></View><View style={styles.score}><Text style={[styles.scoreValue, { color: colors.success }]}>82</Text><Text style={[styles.scoreLabel, { color: colors.mutedForeground }]}>/100</Text></View></View>
    <SectionTitle title="Recommended for you" /><View style={[styles.recommendation, { backgroundColor: colors.secondary }]}><View style={[styles.recommendIcon, { backgroundColor: colors.coral }]}><Feather name="compass" size={18} color={colors.ink} /></View><View style={styles.recommendCopy}><Text style={[styles.recommendTitle, { color: colors.foreground }]}>Strengthen system design</Text><Text style={[styles.recommendBody, { color: colors.mutedForeground }]}>Your answers are strong. Go one level deeper on trade-offs.</Text><Pressable onPress={() => router.push('/practice')}><Text style={[styles.recommendLink, { color: colors.primary }]}>Explore practice →</Text></Pressable></View></View>
  </View>;
}
const styles = StyleSheet.create({ container: { flex: 1, paddingHorizontal: 20, paddingBottom: 90 }, header: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 24 }, greeting: { fontFamily: 'Inter_700Bold', fontSize: 24 }, subtitle: { fontFamily: 'Inter_400Regular', fontSize: 13, marginTop: 5 }, avatar: { width: 45, height: 45, borderRadius: 16, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#FFFFFF', fontFamily: 'Inter_700Bold', fontSize: 13 }, quickStart: { minHeight: 182, borderRadius: 24, padding: 21, flexDirection: 'row', overflow: 'hidden' }, quickCopy: { flex: 1 }, quickEyebrow: { color: '#9DE7C8', fontFamily: 'Inter_700Bold', letterSpacing: 1.5, fontSize: 10 }, quickTitle: { color: '#FFFFFF', fontFamily: 'Inter_700Bold', fontSize: 25, lineHeight: 29, marginTop: 12, maxWidth: 190 }, quickSubtitle: { color: '#BFCBE5', fontFamily: 'Inter_400Regular', fontSize: 12, lineHeight: 18, marginTop: 8, maxWidth: 205 }, startAction: { backgroundColor: '#BCEFD9', borderRadius: 13, paddingHorizontal: 12, paddingVertical: 9, flexDirection: 'row', gap: 7, alignItems: 'center', alignSelf: 'flex-start', marginTop: 15 }, startText: { fontFamily: 'Inter_700Bold', fontSize: 11 }, orbit: { width: 88, height: 88, borderWidth: 1, borderRadius: 44, alignItems: 'center', justifyContent: 'center', alignSelf: 'center', opacity: 0.75 }, stats: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' }, recent: { borderRadius: 18, borderWidth: 1, padding: 13, flexDirection: 'row', alignItems: 'center' }, recentIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, recentCopy: { flex: 1, marginLeft: 12 }, recentTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 14 }, recentMeta: { fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 5 }, score: { flexDirection: 'row', alignItems: 'baseline' }, scoreValue: { fontFamily: 'Inter_700Bold', fontSize: 20 }, scoreLabel: { fontFamily: 'Inter_500Medium', fontSize: 10 }, recommendation: { borderRadius: 20, padding: 16, flexDirection: 'row' }, recommendIcon: { width: 39, height: 39, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, recommendCopy: { flex: 1, marginLeft: 12 }, recommendTitle: { fontFamily: 'Inter_700Bold', fontSize: 14 }, recommendBody: { fontFamily: 'Inter_400Regular', fontSize: 11, lineHeight: 16, marginTop: 5 }, recommendLink: { fontFamily: 'Inter_600SemiBold', fontSize: 11, marginTop: 9 } });
