import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen, SectionTitle } from '@/components/ui';
import { useColors } from '@/hooks/useColors';

const topics = [
  { title: 'System design', body: 'Architecture, trade-offs, scale', icon: 'share-2' as const, color: 'coral' as const, progress: 42 },
  { title: 'Behavioral stories', body: 'Make your impact memorable', icon: 'message-square' as const, color: 'mint' as const, progress: 68 },
  { title: 'Technical depth', body: 'Explain the why, not just the how', icon: 'cpu' as const, color: 'violet' as const, progress: 78 },
];
export default function Practice() {
  const colors = useColors();
  const bg = { coral: colors.coral, mint: colors.mint, violet: colors.violet };
  return <Screen><SectionTitle title="Practice" action="See all topics" /><Text style={[styles.intro, { color: colors.mutedForeground }]}>Short, focused sessions to sharpen the areas that matter most.</Text><Pressable onPress={() => router.push('/create')} style={[styles.hero, { backgroundColor: colors.navy }]}><View style={styles.heroCopy}><Text style={styles.heroEyebrow}>FOCUS MODE</Text><Text style={styles.heroTitle}>One question. Better answers.</Text><Text style={styles.heroBody}>Start a 5-minute drill tailored to your goals.</Text></View><View style={[styles.heroIcon, { backgroundColor: colors.mint }]}><Feather name="target" size={23} color={colors.navy} /></View></Pressable><Pressable onPress={() => router.push('/job-prep')} style={[styles.jobCard, { backgroundColor: colors.secondary }]}><View style={[styles.jobIcon, { backgroundColor: colors.coral }]}><Feather name="briefcase" size={18} color={colors.ink} /></View><View style={styles.jobCopy}><Text style={[styles.jobTitle, { color: colors.foreground }]}>Prepare for a job</Text><Text style={[styles.jobBody, { color: colors.mutedForeground }]}>Compare a job description to your resume.</Text></View><Feather name="arrow-up-right" size={17} color={colors.primary} /></Pressable><SectionTitle title="Your focus areas" />{topics.map((topic) => <Pressable key={topic.title} onPress={() => router.push('/create')} style={[styles.topic, { backgroundColor: colors.card, borderColor: colors.border }]}><View style={[styles.topicIcon, { backgroundColor: bg[topic.color] }]}><Feather name={topic.icon} size={19} color={colors.ink} /></View><View style={styles.topicCopy}><Text style={[styles.topicTitle, { color: colors.foreground }]}>{topic.title}</Text><Text style={[styles.topicBody, { color: colors.mutedForeground }]}>{topic.body}</Text><View style={styles.track}><View style={[styles.fill, { width: `${topic.progress}%`, backgroundColor: colors.primary }]} /></View></View><Text style={[styles.percent, { color: colors.primary }]}>{topic.progress}%</Text></Pressable>)}</Screen>;
}
const styles = StyleSheet.create({ intro: { fontFamily: 'Inter_400Regular', fontSize: 13, lineHeight: 19, marginTop: -4, marginBottom: 20 }, hero: { borderRadius: 23, padding: 19, flexDirection: 'row', minHeight: 152 }, heroCopy: { flex: 1 }, heroEyebrow: { color: '#9DE7C8', fontFamily: 'Inter_700Bold', letterSpacing: 1.4, fontSize: 10 }, heroTitle: { color: '#FFFFFF', fontFamily: 'Inter_700Bold', fontSize: 23, lineHeight: 27, marginTop: 10, maxWidth: 215 }, heroBody: { color: '#BFCBE5', fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 8 }, heroIcon: { width: 48, height: 48, borderRadius: 16, alignItems: 'center', justifyContent: 'center', alignSelf: 'center' }, jobCard: { borderRadius: 18, padding: 13, flexDirection: 'row', alignItems: 'center', marginTop: 11 }, jobIcon: { width: 40, height: 40, borderRadius: 13, alignItems: 'center', justifyContent: 'center' }, jobCopy: { flex: 1, marginLeft: 11 }, jobTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, jobBody: { fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 4 }, topic: { borderRadius: 18, borderWidth: 1, padding: 13, flexDirection: 'row', alignItems: 'center', marginBottom: 10 }, topicIcon: { width: 42, height: 42, borderRadius: 14, alignItems: 'center', justifyContent: 'center' }, topicCopy: { flex: 1, marginLeft: 12 }, topicTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 14 }, topicBody: { fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 4 }, track: { height: 5, backgroundColor: '#EEF1FA', borderRadius: 5, marginTop: 10, overflow: 'hidden' }, fill: { height: 5, borderRadius: 5 }, percent: { fontFamily: 'Inter_700Bold', fontSize: 12, marginLeft: 8 } });