import { Feather } from '@expo/vector-icons';
import { router } from 'expo-router';
import React from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { Screen, Stat } from '@/components/ui';
import { useApp } from '@/context/AppContext';
import { useColors } from '@/hooks/useColors';

export default function Profile() {
  const colors = useColors();
  const { signOut } = useApp();
  return <Screen><View style={styles.profileHead}><View style={[styles.avatar, { backgroundColor: colors.navy }]}><Text style={styles.avatarText}>MK</Text></View><View style={styles.profileCopy}><Text style={[styles.name, { color: colors.foreground }]}>Meraj Khan</Text><Text style={[styles.email, { color: colors.mutedForeground }]}>meraj.khan@email.com</Text><View style={[styles.role, { backgroundColor: colors.accent }]}><Text style={[styles.roleText, { color: colors.accentForeground }]}>Flutter Developer</Text></View></View><Pressable onPress={() => router.push('/settings')} style={[styles.settings, { backgroundColor: colors.secondary }]}><Feather name="settings" size={18} color={colors.foreground} /></Pressable></View><View style={styles.stats}><Stat label="Interviews" value="12" icon="layers" /><Stat label="Avg. score" value="78%" icon="trending-up" /></View><View style={styles.stats}><Stat label="Best score" value="91%" icon="award" /><Stat label="Streak" value="4 days" icon="zap" /></View><Text style={[styles.section, { color: colors.foreground }]}>Account</Text>{[['file-text', 'My resumes', '1 resume saved', '/resume'], ['bell', 'Notifications', 'Stay on track', '/settings'], ['sliders', 'Preferences', 'Theme, voice, language', '/settings']].map(([icon, title, detail, path]) => <Pressable key={title} onPress={() => router.push(path as never)} style={[styles.menu, { borderBottomColor: colors.border }]}><View style={[styles.menuIcon, { backgroundColor: colors.secondary }]}><Feather name={icon as keyof typeof Feather.glyphMap} size={17} color={colors.primary} /></View><View style={styles.menuCopy}><Text style={[styles.menuTitle, { color: colors.foreground }]}>{title}</Text><Text style={[styles.menuDetail, { color: colors.mutedForeground }]}>{detail}</Text></View><Feather name="chevron-right" size={17} color={colors.mutedForeground} /></Pressable>)}<Pressable onPress={() => { signOut(); router.replace('/login'); }} style={styles.logout}><Feather name="log-out" size={17} color={colors.destructive} /><Text style={[styles.logoutText, { color: colors.destructive }]}>Log out</Text></Pressable></Screen>;
}
const styles = StyleSheet.create({ profileHead: { flexDirection: 'row', alignItems: 'center', paddingTop: 12, paddingBottom: 28 }, avatar: { width: 72, height: 72, borderRadius: 24, alignItems: 'center', justifyContent: 'center' }, avatarText: { color: '#FFFFFF', fontFamily: 'Inter_700Bold', fontSize: 20 }, profileCopy: { flex: 1, marginLeft: 14 }, name: { fontFamily: 'Inter_700Bold', fontSize: 20 }, email: { fontFamily: 'Inter_400Regular', fontSize: 11, marginTop: 4 }, role: { borderRadius: 9, paddingHorizontal: 8, paddingVertical: 5, alignSelf: 'flex-start', marginTop: 9 }, roleText: { fontFamily: 'Inter_600SemiBold', fontSize: 10 }, settings: { width: 40, height: 40, borderRadius: 14, alignItems: 'center', justifyContent: 'center', alignSelf: 'flex-start' }, stats: { flexDirection: 'row', justifyContent: 'space-between' }, section: { fontFamily: 'Inter_700Bold', fontSize: 17, marginTop: 25, marginBottom: 8 }, menu: { minHeight: 66, borderBottomWidth: 1, flexDirection: 'row', alignItems: 'center' }, menuIcon: { width: 36, height: 36, borderRadius: 12, alignItems: 'center', justifyContent: 'center' }, menuCopy: { flex: 1, marginLeft: 12 }, menuTitle: { fontFamily: 'Inter_600SemiBold', fontSize: 13 }, menuDetail: { fontFamily: 'Inter_400Regular', fontSize: 10, marginTop: 3 }, logout: { flexDirection: 'row', alignItems: 'center', gap: 8, marginTop: 24, marginBottom: 20 }, logoutText: { fontFamily: 'Inter_600SemiBold', fontSize: 13 } });